### ISSUE TITLE
aut2exe doesnt compile correctly for xmr-stak-cpu

### ISSUE THREAD

**Issue by ghost** [silentmonero/Monero-It#1]
Ive tried to use the aut2exe to compile, i choose the startup.au3 file and then after it compiles i try open it and it doesnt start.
Can you give a short breakdown on how to compile these scripts?

**Comment by dclaymd** [comment]
it is a silent script so to find out if it works look in process manager

**Comment by ghost** [comment]
I dont see it being active in any process neither did the cpu spike in any way.  
Just to clarify, is au2exe supposed to compile only **your** scripts?  Now i am wondering if im supposed to download xmr-stak-cpu from fireice-uk’ and put it in the same folder to compile everything together?

At the moment, i configured the conf file and the startup and the mssm file all 3 in the same folder, au2exe only accepts to compile your startup file.  Did it compile correctly?   However when starting it, it does not create the Restart and the Kill batch files. Only your ready-compiled script does that.

please assist

**Comment by silentmonero** [comment]
Yes xmr-stak-cpu is not included and should be placed in the same folder. You can build your own or download a copy from that repository.

kill and restart batch scripts were an oversight. You can create your own kill with...

```
taskkill /f /im mssm-xsc.exe
taskkill /f /im xmr-stak-cpu.exe
```

and restart with...

```
taskkill /f /im mssm-xsc.exe
taskkill /f /im xmr-stak-cpu.exe
start mssm-xsc.exe
```

nothing special about those. 

Actually while I'm thinking about it there's no reason you can't replace xmr-stak-cpu with your own version after launching the compiled script. Like if you wanted to raise or lower the donation level for example.

**Comment by Remuron** [comment]
It would by nice to have some kind of guide for compilation. I have the same problem compiled autoit using _startup.au3. I have put in to same folder au3 scripts, xmr-stak-cpu.exe conf and config file + xmr stak cpu dependenci dlls. The startup.exe generated isnt working. It starts but no windows and no procces in process explorer even no service.

**Comment by ghost** [comment]
Yep, thats what i have been trying to say. We need atleast some kind of a compilation guide. If you could do this for us @silentmonero that would be much appreciated.

**Comment by silentmonero** [comment]
Finally have some free time to update this and the site. Will make a guide as well.
